### ISSUE TITLE
triggering redirects?

### ISSUE THREAD

**Issue by tconroy** [ayonli/next-controller#1]
Hello! Great work on `next-controller`. Really love the clean API as an alternative to function API route handlers!

I was curious on what the recommended approach is for redirecting a user to another route. I noticed you can throw a 300 or 301 status code:
```
throw new HttpException(301);
```

However not sure how to trigger a redirect to a desired route. 

I noticed the `this.res` object lacks the `res.redirect([status, ] path)` method from Node `res`, so curious what the recommended way to do a redirect is?

**Comment by hyurl** [comment]
Sorry for responding so late. The reason why there isn't a `res.redirect([status, ] path)` is that it is an *express-like* function, **next-controller** does not force the user to use a specific framework (not even **next** itself) but allows us to use any framework we like instead. But yes there is a to perform a redirect, to do so, just declare the type of the `req` and `res` property explicitly in your controller, for example, if you're using **express**:

```ts
@api
export default class MyController extends ApiController {
    protected req: Express.Request;
    protected res: Express.Response;

    get() {
        const res = this.res; // now `res` has a redirect function since it's included in express
    }
}
```

**next** itself also has a dedicated *Reponse* interface, just declare it in the controller and you're free to use. Don't throw an HttpException if the status code is not `4xx` or `5xx`, it's confusing.
